// AUTO-GENERATED by prepare-gallery.mjs — do not edit manually
// To add a new icon set, update scripts/icon-set-configs.mjs

export interface IconSetGalleryConfig {
  label: string;
  packageName: string;
  cssPrefix: string;
  wrapperClass: string;
  primaryVar: string;
  secondaryVar: string;
  shortPrimaryVar: string;
  shortSecondaryVar: string;
  chunkPath: string;
  chunkSize: number;
  categoryIcons: Record<string, string>;
}

export const ICON_SET_CONFIG: Record<string, IconSetGalleryConfig> = {
  lucide: {
    label: "Lucide",
    packageName: "animated-lucide-react",
    cssPrefix: "al",
    wrapperClass: "al-icon-wrapper",
    primaryVar: "--animated-lucide-primary",
    secondaryVar: "--animated-lucide-secondary",
    shortPrimaryVar: "--al-primary",
    shortSecondaryVar: "--al-secondary",
    chunkPath: "/data/lucide",
    chunkSize: 200,
    categoryIcons: {
          "all": "layers",
          "arrows": "arrow-right",
          "communication": "mail",
          "media": "play",
          "files": "file-text",
          "ui": "settings",
          "status": "bell",
          "weather": "sun",
          "objects": "home",
          "editing": "pencil",
          "people": "user",
          "navigation": "map-pin",
          "data": "bar-chart-2",
          "security": "shield",
          "development": "code"
    },
  },
  heroicons: {
    label: "Heroicons",
    packageName: "animated-heroicons-react",
    cssPrefix: "ah",
    wrapperClass: "ah-icon-wrapper",
    primaryVar: "--animated-heroicon-primary",
    secondaryVar: "--animated-heroicon-secondary",
    shortPrimaryVar: "--ah-primary",
    shortSecondaryVar: "--ah-secondary",
    chunkPath: "/data/heroicons",
    chunkSize: 100,
    categoryIcons: {
          "all": "squares-2x2",
          "arrows": "arrow-right",
          "communication": "envelope",
          "media": "play",
          "files": "document-text",
          "ui": "cog",
          "status": "bell",
          "weather": "sun",
          "objects": "home",
          "editing": "pencil",
          "people": "user",
          "navigation": "map-pin",
          "data": "chart-bar",
          "security": "shield-check",
          "development": "code-bracket"
    },
  }
};

export const ICON_SET_KEYS = ["lucide","heroicons"] as const;
export type IconSet = typeof ICON_SET_KEYS[number];
